In [ ]:
Time (h) Temperature (°C) Voltage (V) Current (A) Charge (%)
0 32 400 20 95
1 35 395 22 88
2 38 390 25 80
3 40 385 28 70
4 42 380 30 60
5 45 375 32 48

In [9]:
data = {
    "0" : [32,400,20,95],
    "1" : [35,395,22,88],
    "2" : [38,390,25,80],
    "3" : [40,385,28,70],
    "4" : [42,380,30,60],
    "5" : [45,375,32,48],

}

for time , values in data.items():
    print("Time:" , time)
    print("Temperature: ",values[0])
    print("Voltage: ", values[1])
    print("Current: ",values[2])
    print("Charge: ",values[3])
    print("\n")


Time: 0
Temperature:  32
Voltage:  400
Current:  20
Charge:  95


Time: 1
Temperature:  35
Voltage:  395
Current:  22
Charge:  88


Time: 2
Temperature:  38
Voltage:  390
Current:  25
Charge:  80


Time: 3
Temperature:  40
Voltage:  385
Current:  28
Charge:  70


Time: 4
Temperature:  42
Voltage:  380
Current:  30
Charge:  60


Time: 5
Temperature:  45
Voltage:  375
Current:  32
Charge:  48




In [11]:
for time,values in data.items():
  if(values[0] > 40):
      print("High Temperature Alert")
  else:
    print("Temperature Normal")

Temperature Normal
Temperature Normal
Temperature Normal
Temperature Normal
High Temperature Alert
High Temperature Alert


In [12]:
for time,values in data.items():
  if(values[3] < 50):
      print("“Low Battery Alert”")
  else:
    print("“Battery Charge Normal”")

“Battery Charge Normal”
“Battery Charge Normal”
“Battery Charge Normal”
“Battery Charge Normal”
“Battery Charge Normal”
“Low Battery Alert”


In [17]:
def battery_status(charge):
        if(charge > 70):
            print("High")
        elif(50 <= charge <=70):
           print("Medium")
        else:
           print("Low")

for key,values in data.items():
    battery_status(values[3])
    print("\n")

High


High


High


Medium


Medium


Low




In [22]:
import numpy as np

arr = np.array([[32,400,20,95],
               [35,395,22,88],
               [38,390,25,80],
               [40,385,28,70],
               [42,380,30,60],
               [45,375,32,48]])
print(arr)

[[ 32 400  20  95]
 [ 35 395  22  88]
 [ 38 390  25  80]
 [ 40 385  28  70]
 [ 42 380  30  60]
 [ 45 375  32  48]]


In [24]:
print("Shape: ",arr.shape)

Shape:  (6, 4)


In [32]:
sum=0
i =0
j=0
for j in range(4):
  for i in range(5):
    sum = sum + arr[i][j]
  print("Sum:",sum)
  print("Average:",sum/6)
  print("\n")
  sum=0

Sum: 187
Average: 31.166666666666668


Sum: 1950
Average: 325.0


Sum: 125
Average: 20.833333333333332


Sum: 393
Average: 65.5




In [38]:
i=0
j=0
T_max = arr[0][0]
T_min = arr[0][0]
for i in range(6):
    if(arr[i][0] > T_max):
      T_max = arr[i][0]
    if(arr[i][0] < T_min):
      T_min = arr[i][0]
print("T_max:",T_max )
print("T-min:",T_min)

T_max: 45
T-min: 32


In [43]:
j =1
i =0
arr1 = np.array
for i in range(6):
  arr1 = np.append(arr1, arr[i][1])
print(arr1)

[<built-in function array> 400 395 390 385 380 375]


In [45]:
j =0
i =0
temp = np.array
for i in range(6):
  if(arr[i][0] > 40):
      temp = np.append(temp, arr[i][0])
print(temp)

[<built-in function array> 42 45]


In [48]:
j =3
i =0
c = np.array
for i in range(6):
  if(arr[i][3] < 50):
      c = np.append(c, arr[i][3])
print(c)

[<built-in function array> 48]


In [51]:
from re import T
import numpy as np
A = np.array([[2, 1],
              [1, 3]])
transpose = A.T
print(transpose)

[[2 1]
 [1 3]]


In [52]:
from re import T
import numpy as np
A = np.array([[2, 1],
              [1, 3]])
transpose = np.linalg.det(A)
print(transpose)

5.000000000000001


In [53]:
from re import T
import numpy as np
A = np.array([[2, 1],
              [1, 3]])
transpose = np.linalg.inv(A)
print(transpose)

[[ 0.6 -0.2]
 [-0.2  0.4]]
